name: prova11
favicon: null
layout_spectrum: 0.25091
typography_spectrum: 0.55341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#230e0b'
    - '#e9864b'
    - '#7d4b3c'
    - '#f1caa9'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
