name: prova11
favicon: null
layout_spectrum: 0.25091
typography_spectrum: 0.55341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8eb0ed'
    - '#827800'
    - '#d8bc00'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
